# program 1 for Reshaping the data

In [1]:
import numpy as np

In [3]:
array1 = np.arange(8)

In [4]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7])

In [5]:
# shape array with 2 row 4 columns

In [6]:
array2 =np.arange(8).reshape(2,4)  #reshape(row num,columns num)
array2

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [8]:
# shape array with 2 row 4 columns
array3 =np.arange(8).reshape(4,2)  #reshape(row num,columns num)
array3

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [9]:
#constuct 3D array
arr4 = np.arange(8).reshape(2,2,2)
arr4

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

# Program 2 for assigning the data

In [10]:
import pandas as pd

In [11]:
data= {'Name': ['Jai','Princi','Gaurav','Anju','Ravi','Natasha','Riya'],
      'Age': [17,17,18,17,18,17,17],
      'Gender': ['M','F','M','M','M','F','F'],
      'Marks': [90,76,'NaN',74,65,'NaN',71]}

In [12]:
df = pd.DataFrame(data)
df

Name  Age Gender Marks
0      Jai   17      M    90
1   Princi   17      F    76
2   Gaurav   18      M   NaN
3     Anju   17      M    74
4     Ravi   18      M    65
5  Natasha   17      F   NaN
6     Riya   17      F    71

In [13]:
#Prigram 3
#categorise gender or separate male and female
df['Gender'] = df['Gender'].map({'M':0,'F':1}).astype(float)
df

Name  Age  Gender Marks
0      Jai   17     0.0    90
1   Princi   17     1.0    76
2   Gaurav   18     0.0   NaN
3     Anju   17     0.0    74
4     Ravi   18     0.0    65
5  Natasha   17     1.0   NaN
6     Riya   17     1.0    71

# for filtering the data

In [17]:
import pandas as pd


In [21]:
data1 = {
  "name": ["Sally", "Mary", "John"],
  "age": [50, 40, 30],
  "qualified": [True, False, False]
}

In [22]:
df = pd.DataFrame(data1)
df

name  age  qualified
0  Sally   50       True
1   Mary   40      False
2   John   30      False

In [23]:
newdf = df.filter(items=["name", "age"])
newdf

name  age
0  Sally   50
1   Mary   40
2   John   30

# Merging the data

In [24]:
data2 = {
  "name": ["Sally", "Mary", "John"],
  "age": [50, 40, 30]
}

In [25]:
data3 = {
  "name": ["Sally", "Peter", "Micky"],
  "age": [77, 44, 22]
}

In [29]:
df1 = pd.DataFrame(data2)
df1

name  age
0  Sally   50
1   Mary   40
2   John   30

In [30]:
df2 = pd.DataFrame(data3)
df2

name  age
0  Sally   77
1  Peter   44
2  Micky   22

In [39]:
merg = df1.merge(df2,how='left')
merg

name  age
0  Sally   50
1   Mary   40
2   John   30

In [43]:
pd.concat([df1,df2])

name  age
0  Sally   50
1   Mary   40
2   John   30
0  Sally   77
1  Peter   44
2  Micky   22