In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
df =pd.read_csv('8.spam email detector.csv') #spam=1,not=0
df

text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5721  Subject: re : research and development charges...     0
5722  Subject: re : receipts from visit  jim ,  than...     0
5723  Subject: re : enron case study update  wow ! a...     0
5724  Subject: re : interest  david ,  please , call...     0
5725  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5726 rows x 2 columns]

In [4]:
df['spam'].value_counts() #for count spam email

0    4359
1    1367
Name: spam, dtype: int64

In [6]:
df.drop_duplicates(inplace=True) #if have any duplicate value then drop

In [7]:
df

text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5721  Subject: re : research and development charges...     0
5722  Subject: re : receipts from visit  jim ,  than...     0
5723  Subject: re : enron case study update  wow ! a...     0
5724  Subject: re : interest  david ,  please , call...     0
5725  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5693 rows x 2 columns]

In [8]:
df['spam'].value_counts()

0    4326
1    1367
Name: spam, dtype: int64

In [9]:
 # above we understand that duplicates value exist in hame

In [10]:
df.isnull().sum()

text    0
spam    0
dtype: int64

# separate x and y

In [12]:
#text is independent and spam is dependent
x= df.text.values


In [13]:
y=df.spam.values

# split dataset

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
xtrain,xtest,ytrain,ytest= train_test_split(x,y,test_size=0.2)#o.2 means 20% tesst

# Data Preprocessing

In [17]:
from sklearn.feature_extraction.text import CountVectorizer

In [18]:
cv = CountVectorizer()

In [19]:
x_train= cv.fit_transform(xtrain)

In [23]:
x_train.toarray() #value will be insert for every row,kon wort gulo ktobar ache ta dekhabe

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [47]:
x_test = cv.transform(xtest)

In [48]:
x_test = cv.transform(xtest)

In [49]:
x_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [1, 2, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [5, 0, 0, ..., 0, 0, 0]], dtype=int64)

# ML Algorithm

In [24]:
from sklearn.naive_bayes import MultinomialNB

In [25]:
mnb = MultinomialNB()

In [26]:
mnb.fit(x_train,ytrain)

MultinomialNB()

# Show Accuracy

In [31]:
mnb.score(x_test,ytest)

0.9885864793678666

# Check email ham or spam

In [44]:
email = ['hey i am looking for bangla machin learning tutorial', 'yow will win a iphone x free so ,you send a address']

In [45]:
email =cv.transform(email)

In [46]:
mnb.predict(email)

array([0, 1], dtype=int64)

In [ ]:
# 0 means prothon ta ham mail and 1 means porer ta spam email